### ISSUE TITLE
Hello. There is an issue with python3.10 related to behabiour component:  File "/usr/local/lib/python3.10/dist-packages/spade/behaviour.py", line 63, in  set_agent     self.queue = asyncio.Queue(loop=self.agent.loop)   File "/usr/lib/python3.10/asyncio/queues.py", line 34, in __init__     super().__init__(loop=loop)   File "/usr/lib/python3.10/asyncio/mixins.py", line 17, in __init__     raise TypeError( TypeError: As of 3.10, the *loop* parameter was removed from Queue() since it is  no longer necessary

### ISSUE THREAD

**Issue by jbmere** [javipalanca/spade#106]
* SPADE version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by jbmere** [comment]
Spade version 3.2.2
Python3: 3.10.6
Operating System: Ububtu 22.04

**Description:**

It appears an inner error because a non needed parameter:

 File "/usr/local/lib/python3.10/dist-packages/spade/behaviour.py", line 63, in
 set_agent
    self.queue = asyncio.Queue(loop=self.agent.loop)
  File "/usr/lib/python3.10/asyncio/queues.py", line 34, in __init__
    super().__init__(loop=loop)
  File "/usr/lib/python3.10/asyncio/mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Queue() since it is
 no longer necessary

**Request**
Could it be possible to upgrade the package to the new python3 versions? It does work in 3.8

**Comment by 0x1F602** [comment]
@jbmere thats in the devel branch, if you switch over it does work

**Comment by jbmere** [comment]
Thank yu for your quick reaction. However, I'm afraid the issue is still there:

File "/usr/local/lib/python3.10/dist-packages/spade/agent.py", line 137, in _a
sync_start
    await self.setup()
  File "/mnt/sda/home/jb/./tmp.QuSUhh3us2/launcher.py", line 325, in setup
    self.add_behaviour(b, template)
  File "/usr/local/lib/python3.10/dist-packages/spade/agent.py", line 251, in ad
d_behaviour
    behaviour.set_agent(agent=self)
  **File "/usr/local/lib/python3.10/dist-packages/spade/behaviour.py", line 63, in
 set_agent
    self.queue = asyncio.Queue(loop=self.agent.loop)
  File "/usr/lib/python3.10/asyncio/queues.py", line 34, in __init__
    super().__init__(loop=loop)**
  File "/usr/lib/python3.10/asyncio/mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Queue() since it is
 no longer necessary
Traceback (most recent call last):
  File "/mnt/sda/home/jb/./tmp.QuSUhh3us2/launcher.py", line 5, in <module>
    from spade import quit_spade
ImportError: cannot import name 'quit_spade' from 'spade' (**/usr/local/lib/python
3.10/dist-packages/spade-3.2.3-py3.10.egg/spade/__init__.py**)

Any additional suggestion?

**Comment by 0x1F602** [comment]
@jbmere Send a more complete example of code, not just the stacktrace, thanks

**Comment by javipalanca** [comment]
Upgrade to SPADE 3.3 where this is fixed.
